namespace TalentPilot.Application.Admin.TenantProfiles;

public sealed record TenantProfileSettings(
    Guid TenantId,
    string DisplayName,
    string Slug,
    string Domain,
    string AdminContactEmail,
    string DefaultTimezone,
    string DefaultCurrency,
    string Status,
    string CareerDisplayName,
    string? CompanyAddress,
    string? CompanyCity,
    string? CompanyCountry,
    string? OfficialEmail,
    string? OfficialPhone,
    string PrimaryColor,
    bool CandidateLoginRequired,
    string CandidateCvFormat,
    bool PublicJobsEnabled,
    int InviteExpiryDays,
    int ReapplyCooldownDays,
    string NotificationEmailProvider,
    int UserCount,
    int RoleCount,
    bool SetupComplete,
    string ConfiguredLlmModel,
    string ConfiguredEmbeddingModel,
    string? LogoFileName,
    string? LogoContentType,
    string? LogoContentBase64,
    DateTimeOffset UpdatedAt);

public sealed record UpdateTenantProfileSettingsInput(
    string DisplayName,
    string Slug,
    string Domain,
    string AdminContactEmail,
    string DefaultTimezone,
    string DefaultCurrency,
    string Status,
    string CareerDisplayName,
    string? CompanyAddress,
    string? CompanyCity,
    string? CompanyCountry,
    string? OfficialEmail,
    string? OfficialPhone,
    string PrimaryColor,
    bool CandidateLoginRequired,
    string CandidateCvFormat,
    bool PublicJobsEnabled,
    int InviteExpiryDays,
    int ReapplyCooldownDays,
    string NotificationEmailProvider,
    string? LogoFileName,
    string? LogoContentType,
    string? LogoContentBase64);

public sealed record SlugAvailabilityResponse(string Slug, bool Available);
